# Generated by Django 2.2.4 on 2020-04-27 22:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videogame_name', models.CharField(max_length=100)),
                ('videogame_console', models.CharField(max_length=100)),
                ('v_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('videogame_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('coll_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videogames', to='crm.Collector')),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('console_model', models.CharField(max_length=100)),
                ('console_color', models.CharField(max_length=100)),
                ('console_brand', models.CharField(max_length=100)),
                ('console_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('coll_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consoles', to='crm.Collector')),
            ],
        ),
    ]
